apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-nodes
  namespace: logistream
  labels:
    strimzi.io/cluster: logistream-kafka
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi